/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * OutputView.java
 *
 * Created on Oct 14, 2009, 2:09:07 AM
 */

package opendatcom;

import java.util.LinkedList;
import javax.swing.JTextPane;

/**
 *
 * @author -B-
 */
public class OutputView extends javax.swing.JPanel {

    String outputData;
    LinkedList<AbstractController> controllers;

    /** Creates new form OutputView */
    public OutputView() {
        initComponents();
        outputData = "";
        controllers = new LinkedList<AbstractController>();
    }

    /**
     * Registers a controller with the view. The order matters! Controllers will
     * be accessed in the order they are added.
     * @param control The controller to register.
     */
    public void registerController(AbstractController control)
    {
        controllers.add(control);
    }

    /**
     * Updates the text in the output's view
     * @return
     */
    public String getControllerOutput()
    {
        String temp = "";
        
        for(int x = 0; x < controllers.size(); x++)
        {
            controllers.get(x).refresh();
            temp += controllers.get(x).generateOutput();
        }

        return temp;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jOutputText = new javax.swing.JTextPane();
        jPanel2 = new javax.swing.JPanel();
        jManualRefresh1 = new javax.swing.JButton();
        jManualRefresh2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jShowDatcomReadable = new javax.swing.JButton();
        jShowHumanReadable = new javax.swing.JButton();
        jManualRevert = new javax.swing.JButton();
        jSetData = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jDrawPane = new javax.swing.JPanel();

        setName("Form"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(opendatcom.OpenDatcomApp.class).getContext().getResourceMap(OutputView.class);
        jOutputText.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("jOutputText.border.border.title"), javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION))); // NOI18N
        jOutputText.setEditable(false);
        jOutputText.setFocusable(false);
        jOutputText.setName("jOutputText"); // NOI18N
        jScrollPane1.setViewportView(jOutputText);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel2.border.title"))); // NOI18N
        jPanel2.setName("jPanel2"); // NOI18N

        jManualRefresh1.setText(resourceMap.getString("jManualRefresh1.text")); // NOI18N
        jManualRefresh1.setName("jManualRefresh1"); // NOI18N

        jManualRefresh2.setText(resourceMap.getString("jManualRefresh2.text")); // NOI18N
        jManualRefresh2.setName("jManualRefresh2"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jManualRefresh2, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(jManualRefresh1, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jManualRefresh2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jManualRefresh1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel1.border.title"))); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        jShowDatcomReadable.setText(resourceMap.getString("jShowDatcomReadable.text")); // NOI18N
        jShowDatcomReadable.setName("jShowDatcomReadable"); // NOI18N
        jShowDatcomReadable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jShowDatcomReadableActionPerformed(evt);
            }
        });

        jShowHumanReadable.setText(resourceMap.getString("jShowHumanReadable.text")); // NOI18N
        jShowHumanReadable.setName("jShowHumanReadable"); // NOI18N
        jShowHumanReadable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jShowHumanReadableActionPerformed(evt);
            }
        });

        jManualRevert.setText(resourceMap.getString("jManualRevert.text")); // NOI18N
        jManualRevert.setEnabled(false);
        jManualRevert.setName("jManualRevert"); // NOI18N

        jSetData.setText(resourceMap.getString("jSetData.text")); // NOI18N
        jSetData.setName("jSetData"); // NOI18N
        jSetData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSetDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jManualRevert, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(jSetData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(jShowDatcomReadable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(jShowHumanReadable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jShowHumanReadable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jShowDatcomReadable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jManualRevert)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSetData)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel3.setName("jPanel3"); // NOI18N

        jDrawPane.setBackground(resourceMap.getColor("jDrawPane.background")); // NOI18N
        jDrawPane.setName("jDrawPane"); // NOI18N

        javax.swing.GroupLayout jDrawPaneLayout = new javax.swing.GroupLayout(jDrawPane);
        jDrawPane.setLayout(jDrawPaneLayout);
        jDrawPaneLayout.setHorizontalGroup(
            jDrawPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 163, Short.MAX_VALUE)
        );
        jDrawPaneLayout.setVerticalGroup(
            jDrawPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDrawPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDrawPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jSetDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSetDataActionPerformed
        jOutputText.setText(outputData);
    }//GEN-LAST:event_jSetDataActionPerformed

    private void jShowHumanReadableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jShowHumanReadableActionPerformed
        String temp = getControllerOutput();
        jOutputText.setText(temp);
    }//GEN-LAST:event_jShowHumanReadableActionPerformed

    private void jShowDatcomReadableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jShowDatcomReadableActionPerformed
        String temp = getControllerOutput();
        temp = removeComments(temp);
        temp = temp.replaceAll("\t", "");
        temp = consolidateSpacing(temp);
        temp = datcomFormat(temp);
        jOutputText.setText(temp);
    }//GEN-LAST:event_jShowDatcomReadableActionPerformed

    public String datcomFormat(String target)
    {
        String [] section = target.split("$");
        String [] subsection = null;
        target = "";
        
        for(int x = 0; x < section.length; x++)
        {
            subsection = section[x].split("\n");
            for(int y = 0; y < subsection.length; y++)
            {
                target += " " + subsection[y];
            }
        }
        return target;
    }
    
    /**
     * Removes all the comment lines from the input data.
     * @param target The input data.
     * @return The The input data - any # comments.
     */
    public String removeComments(String target)
    {
        String [] temp = target.split("\n");
        target = "";

        for(int x = 0; x < temp.length; x++)
        {
            temp[x] += "\n";
            if(temp[x].charAt(0) == '#')
            {
                temp[x] = "";
            }
            target += temp[x];
        }
        return target;
    }

    public String consolidateSpacing(String target)
    {
        String [] temp = target.split("\n");
        target = "";
        int currentSpacing = 0;
        int potentialSpacing = 0;
        int maxLineSize = 50;
        
        for(int x = 0; x < temp.length; x++)
        {
            currentSpacing = temp[x].length();
            target += temp[x] + " ";
            for(int y = (x+1); y < temp.length; y++)
            {
               potentialSpacing = currentSpacing + temp[y].length();
               if(potentialSpacing <= maxLineSize)
                {
                    currentSpacing = potentialSpacing;
                    target += temp[y];
                    temp[y] = "";
                }
               else
               {
                   target += "\n";
                   break;
               }
            }
           currentSpacing = 0;
        }
        return target;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jDrawPane;
    private javax.swing.JButton jManualRefresh1;
    private javax.swing.JButton jManualRefresh2;
    private javax.swing.JButton jManualRevert;
    private javax.swing.JTextPane jOutputText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jSetData;
    private javax.swing.JButton jShowDatcomReadable;
    private javax.swing.JButton jShowHumanReadable;
    // End of variables declaration//GEN-END:variables

    public JTextPane getjOutputText() {
        return jOutputText;
    }

    public void setjOutputText(JTextPane jOutputText) {
        this.jOutputText = jOutputText;
    }

    public String getOutputData() {
        return outputData;
    }

    public void setOutputData(String outputData) {
        this.outputData = outputData;
        jOutputText.setText(outputData);
    }

    public void runDATCOM(String target, String workingPath, String sectionHeader){
       //declare classes needed for writing output file, creating a batch file,
       //and running the program.
        runDatcom runBabyRun = new runDatcom();
        getFor005 printFile = new getFor005();
        writeBAT createBatchFile = new writeBAT();

       // If user selects to run DATCOM
        String[] openDatcom = {workingPath + "\\Datcom.bat"};
        String mkDir = "cmd /c mkdir " + workingPath + "\\" + sectionHeader;

        runBabyRun.executeDatcom(mkDir);

        printFile.writeFile(workingPath + "\\" + sectionHeader, "for005.dat", target);

        createBatchFile.writeFile(workingPath, sectionHeader);

        runBabyRun.executeDatcom(openDatcom);

        /*Review Panel Commands - TODO:
        for005panel =  this;
        reviewPanel = new REVIEW(workingPath + "\\" + sectionHeader + "\\for006.dat", for005panel, mainClass);
        reviewPanel.showFor006();
        */
    }
}
