/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SynthesisView.java
 *
 * Created on Oct 13, 2009, 11:01:58 PM
 */

package opendatcom;

import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author -B-
 */
public class SynthesisView extends javax.swing.JPanel {

    String outputData;
    SynthesisController controller;
    /** Creates new form SynthesisView */
    public SynthesisView() {
        initComponents();
        controller = new SynthesisController(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel53 = new javax.swing.JPanel();
        jPanel56 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jXWText = new javax.swing.JTextField();
        jLabel220 = new javax.swing.JLabel();
        jALIWText = new javax.swing.JTextField();
        jXCGText = new javax.swing.JTextField();
        jLabel228 = new javax.swing.JLabel();
        jLabel229 = new javax.swing.JLabel();
        jLabel232 = new javax.swing.JLabel();
        jALIHText = new javax.swing.JTextField();
        jZWText = new javax.swing.JTextField();
        jZCGText = new javax.swing.JTextField();
        jLabel241 = new javax.swing.JLabel();
        jLabel242 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jXVFText = new javax.swing.JTextField();
        jLabel235 = new javax.swing.JLabel();
        jXVText = new javax.swing.JTextField();
        jXHText = new javax.swing.JTextField();
        jLabel236 = new javax.swing.JLabel();
        jLabel237 = new javax.swing.JLabel();
        jLabel238 = new javax.swing.JLabel();
        jZVText = new javax.swing.JTextField();
        jZVFText = new javax.swing.JTextField();
        jZHText = new javax.swing.JTextField();
        jLabel239 = new javax.swing.JLabel();
        jLabel243 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jSetValues = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jShowReference = new javax.swing.JButton();
        jFlightHeaderText4 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jSynthHeader = new javax.swing.JTextArea();
        jSynthDrawPane = new javax.swing.JPanel();
        jPanel58 = new javax.swing.JPanel();
        jLabel240 = new javax.swing.JLabel();

        setName("Form"); // NOI18N

        jPanel53.setName("jPanel53"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(opendatcom.OpenDatcomApp.class).getContext().getResourceMap(SynthesisView.class);
        jPanel56.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel56.border.title"))); // NOI18N
        jPanel56.setName("jPanel56"); // NOI18N

        jPanel11.setName("jPanel11"); // NOI18N

        jXWText.setName("jXWText"); // NOI18N

        jLabel220.setText(resourceMap.getString("jLabel220.text")); // NOI18N
        jLabel220.setToolTipText(resourceMap.getString("jLabel220.toolTipText")); // NOI18N
        jLabel220.setName("jLabel220"); // NOI18N

        jALIWText.setName("jALIWText"); // NOI18N

        jXCGText.setName("jXCGText"); // NOI18N

        jLabel228.setText(resourceMap.getString("jLabel228.text")); // NOI18N
        jLabel228.setToolTipText(resourceMap.getString("jLabel228.toolTipText")); // NOI18N
        jLabel228.setName("jLabel228"); // NOI18N

        jLabel229.setText(resourceMap.getString("jLabel229.text")); // NOI18N
        jLabel229.setToolTipText(resourceMap.getString("jLabel229.toolTipText")); // NOI18N
        jLabel229.setName("jLabel229"); // NOI18N

        jLabel232.setText(resourceMap.getString("jLabel232.text")); // NOI18N
        jLabel232.setToolTipText(resourceMap.getString("jLabel232.toolTipText")); // NOI18N
        jLabel232.setName("jLabel232"); // NOI18N

        jALIHText.setName("jALIHText"); // NOI18N

        jZWText.setName("jZWText"); // NOI18N

        jZCGText.setName("jZCGText"); // NOI18N

        jLabel241.setText(resourceMap.getString("jLabel241.text")); // NOI18N
        jLabel241.setToolTipText(resourceMap.getString("jLabel241.toolTipText")); // NOI18N
        jLabel241.setName("jLabel241"); // NOI18N

        jLabel242.setText(resourceMap.getString("jLabel242.text")); // NOI18N
        jLabel242.setToolTipText(resourceMap.getString("jLabel242.toolTipText")); // NOI18N
        jLabel242.setName("jLabel242"); // NOI18N

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel229)
                    .addComponent(jLabel228)
                    .addComponent(jLabel232)
                    .addComponent(jLabel220)
                    .addComponent(jLabel241)
                    .addComponent(jLabel242))
                .addGap(64, 64, 64)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jZCGText, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jXCGText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(jXWText, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jZWText, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jALIWText, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jALIHText, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel229)
                    .addComponent(jXCGText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel220)
                    .addComponent(jZCGText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel232)
                    .addComponent(jXWText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel228)
                    .addComponent(jZWText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jALIWText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel241))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jALIHText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel242))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel19.setName("jPanel19"); // NOI18N

        jXVFText.setName("jXVFText"); // NOI18N

        jLabel235.setText(resourceMap.getString("jLabel235.text")); // NOI18N
        jLabel235.setToolTipText(resourceMap.getString("jLabel235.toolTipText")); // NOI18N
        jLabel235.setName("jLabel235"); // NOI18N

        jXVText.setName("jXVText"); // NOI18N

        jXHText.setName("jXHText"); // NOI18N

        jLabel236.setText(resourceMap.getString("jLabel236.text")); // NOI18N
        jLabel236.setToolTipText(resourceMap.getString("jLabel236.toolTipText")); // NOI18N
        jLabel236.setName("jLabel236"); // NOI18N

        jLabel237.setText(resourceMap.getString("jLabel237.text")); // NOI18N
        jLabel237.setToolTipText(resourceMap.getString("jLabel237.toolTipText")); // NOI18N
        jLabel237.setName("jLabel237"); // NOI18N

        jLabel238.setText(resourceMap.getString("jLabel238.text")); // NOI18N
        jLabel238.setToolTipText(resourceMap.getString("jLabel238.toolTipText")); // NOI18N
        jLabel238.setName("jLabel238"); // NOI18N

        jZVText.setName("jZVText"); // NOI18N

        jZVFText.setName("jZVFText"); // NOI18N

        jZHText.setName("jZHText"); // NOI18N

        jLabel239.setText(resourceMap.getString("jLabel239.text")); // NOI18N
        jLabel239.setToolTipText(resourceMap.getString("jLabel239.toolTipText")); // NOI18N
        jLabel239.setName("jLabel239"); // NOI18N

        jLabel243.setText(resourceMap.getString("jLabel243.text")); // NOI18N
        jLabel243.setToolTipText(resourceMap.getString("jLabel243.toolTipText")); // NOI18N
        jLabel243.setName("jLabel243"); // NOI18N

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel237)
                    .addComponent(jLabel236)
                    .addComponent(jLabel238)
                    .addComponent(jLabel235)
                    .addComponent(jLabel243)
                    .addComponent(jLabel239))
                .addGap(75, 75, 75)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jZHText, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jXHText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(jXVFText, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jZVFText, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jXVText, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jZVText, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel237)
                    .addComponent(jXHText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel235)
                    .addComponent(jZHText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel238)
                    .addComponent(jXVFText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel236)
                    .addComponent(jZVFText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXVText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel243))
                .addGap(18, 18, 18)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jZVText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel239))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel56Layout = new javax.swing.GroupLayout(jPanel56);
        jPanel56.setLayout(jPanel56Layout);
        jPanel56Layout.setHorizontalGroup(
            jPanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel56Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel56Layout.setVerticalGroup(
            jPanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel22.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel22.border.title"))); // NOI18N
        jPanel22.setName("jPanel22"); // NOI18N

        jPanel23.setName("jPanel23"); // NOI18N

        jSetValues.setText(resourceMap.getString("jSetValues.text")); // NOI18N
        jSetValues.setName("jSetValues"); // NOI18N
        jSetValues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSetValuesActionPerformed(evt);
            }
        });

        jButton10.setText(resourceMap.getString("jButton10.text")); // NOI18N
        jButton10.setEnabled(false);
        jButton10.setName("jButton10"); // NOI18N

        jShowReference.setText(resourceMap.getString("jShowReference.text")); // NOI18N
        jShowReference.setName("jShowReference"); // NOI18N

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSetValues, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(jButton10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(jShowReference, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel23Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSetValues)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jShowReference))
        );

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jFlightHeaderText4.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jFlightHeaderText4.border.title"))); // NOI18N
        jFlightHeaderText4.setName("jFlightHeaderText4"); // NOI18N

        jScrollPane10.setName("jScrollPane10"); // NOI18N

        jSynthHeader.setColumns(20);
        jSynthHeader.setRows(5);
        jSynthHeader.setName("jSynthHeader"); // NOI18N
        jScrollPane10.setViewportView(jSynthHeader);

        javax.swing.GroupLayout jFlightHeaderText4Layout = new javax.swing.GroupLayout(jFlightHeaderText4);
        jFlightHeaderText4.setLayout(jFlightHeaderText4Layout);
        jFlightHeaderText4Layout.setHorizontalGroup(
            jFlightHeaderText4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFlightHeaderText4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                .addContainerGap())
        );
        jFlightHeaderText4Layout.setVerticalGroup(
            jFlightHeaderText4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFlightHeaderText4Layout.createSequentialGroup()
                .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel53Layout = new javax.swing.GroupLayout(jPanel53);
        jPanel53.setLayout(jPanel53Layout);
        jPanel53Layout.setHorizontalGroup(
            jPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel53Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel56, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel53Layout.createSequentialGroup()
                        .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFlightHeaderText4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel53Layout.setVerticalGroup(
            jPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel53Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel56, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jFlightHeaderText4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jSynthDrawPane.setBackground(resourceMap.getColor("jSynthDrawPane.background")); // NOI18N
        jSynthDrawPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jSynthDrawPane.setName("jSynthDrawPane"); // NOI18N

        javax.swing.GroupLayout jSynthDrawPaneLayout = new javax.swing.GroupLayout(jSynthDrawPane);
        jSynthDrawPane.setLayout(jSynthDrawPaneLayout);
        jSynthDrawPaneLayout.setHorizontalGroup(
            jSynthDrawPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 522, Short.MAX_VALUE)
        );
        jSynthDrawPaneLayout.setVerticalGroup(
            jSynthDrawPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );

        jPanel58.setName("jPanel58"); // NOI18N

        jLabel240.setFont(resourceMap.getFont("jLabel240.font")); // NOI18N
        jLabel240.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel240.setText(resourceMap.getString("jLabel240.text")); // NOI18N
        jLabel240.setName("jLabel240"); // NOI18N

        javax.swing.GroupLayout jPanel58Layout = new javax.swing.GroupLayout(jPanel58);
        jPanel58.setLayout(jPanel58Layout);
        jPanel58Layout.setHorizontalGroup(
            jPanel58Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel58Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel240, javax.swing.GroupLayout.DEFAULT_SIZE, 1054, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel58Layout.setVerticalGroup(
            jPanel58Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel58Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel240, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel58, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel53, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSynthDrawPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel58, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel53, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSynthDrawPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(26, 26, 26))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jSetValuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSetValuesActionPerformed
        controller.refresh();
    }//GEN-LAST:event_jSetValuesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jALIHText;
    private javax.swing.JTextField jALIWText;
    private javax.swing.JButton jButton10;
    private javax.swing.JPanel jFlightHeaderText4;
    private javax.swing.JLabel jLabel220;
    private javax.swing.JLabel jLabel228;
    private javax.swing.JLabel jLabel229;
    private javax.swing.JLabel jLabel232;
    private javax.swing.JLabel jLabel235;
    private javax.swing.JLabel jLabel236;
    private javax.swing.JLabel jLabel237;
    private javax.swing.JLabel jLabel238;
    private javax.swing.JLabel jLabel239;
    private javax.swing.JLabel jLabel240;
    private javax.swing.JLabel jLabel241;
    private javax.swing.JLabel jLabel242;
    private javax.swing.JLabel jLabel243;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel53;
    private javax.swing.JPanel jPanel56;
    private javax.swing.JPanel jPanel58;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JButton jSetValues;
    private javax.swing.JButton jShowReference;
    private javax.swing.JPanel jSynthDrawPane;
    private javax.swing.JTextArea jSynthHeader;
    private javax.swing.JTextField jXCGText;
    private javax.swing.JTextField jXHText;
    private javax.swing.JTextField jXVFText;
    private javax.swing.JTextField jXVText;
    private javax.swing.JTextField jXWText;
    private javax.swing.JTextField jZCGText;
    private javax.swing.JTextField jZHText;
    private javax.swing.JTextField jZVFText;
    private javax.swing.JTextField jZVText;
    private javax.swing.JTextField jZWText;
    // End of variables declaration//GEN-END:variables

    public JTextField getjALIHText() {
        return jALIHText;
    }

    public JTextField getjALIWText() {
        return jALIWText;
    }

    public JButton getjButton10() {
        return jButton10;
    }

    public JButton getjButton11() {
        return jShowReference;
    }

    public JButton getjButton9() {
        return jSetValues;
    }

    public JPanel getjFlightHeaderText4() {
        return jFlightHeaderText4;
    }

    public JScrollPane getjScrollPane10() {
        return jScrollPane10;
    }

    public JPanel getjSynthDrawPane() {
        return jSynthDrawPane;
    }

    public JTextArea getjSynthHeader() {
        return jSynthHeader;
    }

    public JTextField getjXCGText() {
        return jXCGText;
    }

    public JTextField getjXHText() {
        return jXHText;
    }

    public JTextField getjXVFText() {
        return jXVFText;
    }

    public JTextField getjXVText() {
        return jXVText;
    }

    public JTextField getjXWText() {
        return jXWText;
    }

    public JTextField getjZCGText() {
        return jZCGText;
    }

    public JTextField getjZHText() {
        return jZHText;
    }

    public JTextField getjZVFText() {
        return jZVFText;
    }

    public JTextField getjZVText() {
        return jZVText;
    }

    public JTextField getjZWText() {
        return jZWText;
    }

    public String getOutputData() {
        return outputData;
    }

    public void setOutputData(String outputData) {
        this.outputData = outputData;
    }


}
