/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FlightConditionsView.java
 *
 * Created on Oct 14, 2009, 12:03:47 AM
 */

package Views;

import Core.OAE_DataLink;
import Core.OAE_LinkedTable;
import Core.OAE_ViewComponent;
import Services.ExcelAdapter;

/**
 *
 * @author -B-
 */
public class FlightConditionsView extends OAE_ViewComponent
{
    static FlightConditionsView self;
    /** Creates new form FlightConditionsView */
    public FlightConditionsView() {
        initComponents();
        ExcelAdapter ea = new ExcelAdapter(jTable);
        initView("FLTCON");
    }

    public void registerLinks()
    {
        parent.addLink(new OAE_LinkedTable("ALSCHD",jTable,  0));
        parent.addLink(new OAE_LinkedTable("ALT",   jTable,   1));
        parent.addLink(new OAE_LinkedTable("MACH",  jTable,     2));
        parent.addLink(new OAE_DataLink("STMACH",   jSTMach,    double.class));
        parent.addLink(new OAE_DataLink("TSMACH",   jTSMach,    double.class));
        parent.addLink(new OAE_DataLink("TR",       jTR,        double.class));
        parent.addLink(new OAE_DataLink("WT",       jWeight,    double.class));
        parent.addLink(new OAE_DataLink("GAMMA",    jGamma,     double.class));
        parent.addLink(new OAE_DataLink("LOOP",     jLoop,      double.class));
        parent.addLink(new OAE_DataLink("SREF",     jSref,      double.class));
        parent.addLink(new OAE_DataLink("BLREF",    jBlref,     double.class));
        parent.addLink(new OAE_DataLink("CBARR",    jCbarr,     double.class));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel13 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jPanel17 = new javax.swing.JPanel();
        jWeight = new javax.swing.JTextField();
        jSTMach = new javax.swing.JTextField();
        jLabel226 = new javax.swing.JLabel();
        jTSMach = new javax.swing.JTextField();
        jLabel227 = new javax.swing.JLabel();
        jGamma = new javax.swing.JTextField();
        jLabel230 = new javax.swing.JLabel();
        jTR = new javax.swing.JTextField();
        jLabel236 = new javax.swing.JLabel();
        jLabel237 = new javax.swing.JLabel();
        jLabel238 = new javax.swing.JLabel();
        jLoop = new javax.swing.JTextField();
        jLabel231 = new javax.swing.JLabel();
        jFlightHeaderText = new javax.swing.JPanel();
        jLabel228 = new javax.swing.JLabel();
        jLabel229 = new javax.swing.JLabel();
        jLabel239 = new javax.swing.JLabel();
        jLabel240 = new javax.swing.JLabel();
        jBlref = new javax.swing.JTextField();
        jSref = new javax.swing.JTextField();
        jCbarr = new javax.swing.JTextField();
        jRoughness = new javax.swing.JComboBox();
        jPanel55 = new javax.swing.JPanel();
        jTitle = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(800, 600));

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(opendatcom.OpenDatcomController.class).getContext().getResourceMap(FlightConditionsView.class);
        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel13.border.title"))); // NOI18N
        jPanel13.setName("jPanel13"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable.setAutoCreateRowSorter(true);
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "AOA", "Altitude", "Mach"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable.setCellSelectionEnabled(true);
        jTable.setDoubleBuffered(true);
        jTable.setDragEnabled(true);
        jTable.setFocusCycleRoot(true);
        jTable.setName("jTable"); // NOI18N
        jScrollPane1.setViewportView(jTable);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel17.border.title"))); // NOI18N
        jPanel17.setName("jPanel17"); // NOI18N

        jWeight.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jWeight.setText(resourceMap.getString("jWeight.text")); // NOI18N
        jWeight.setName("jWeight"); // NOI18N
        jWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jWeightActionPerformed(evt);
            }
        });

        jSTMach.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jSTMach.setName("jSTMach"); // NOI18N

        jLabel226.setText(resourceMap.getString("jLabel226.text")); // NOI18N
        jLabel226.setToolTipText(resourceMap.getString("jLabel226.toolTipText")); // NOI18N
        jLabel226.setName("jLabel226"); // NOI18N

        jTSMach.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTSMach.setName("jTSMach"); // NOI18N

        jLabel227.setText(resourceMap.getString("jLabel227.text")); // NOI18N
        jLabel227.setToolTipText(resourceMap.getString("jLabel227.toolTipText")); // NOI18N
        jLabel227.setName("jLabel227"); // NOI18N

        jGamma.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jGamma.setName("jGamma"); // NOI18N

        jLabel230.setText(resourceMap.getString("jLabel230.text")); // NOI18N
        jLabel230.setToolTipText(resourceMap.getString("jLabel230.toolTipText")); // NOI18N
        jLabel230.setName("jLabel230"); // NOI18N

        jTR.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTR.setName("jTR"); // NOI18N

        jLabel236.setName("jLabel236"); // NOI18N

        jLabel237.setText(resourceMap.getString("jLabel237.text")); // NOI18N
        jLabel237.setToolTipText(resourceMap.getString("jLabel237.toolTipText")); // NOI18N
        jLabel237.setName("jLabel237"); // NOI18N

        jLabel238.setText(resourceMap.getString("jLabel238.text")); // NOI18N
        jLabel238.setToolTipText(resourceMap.getString("jLabel238.toolTipText")); // NOI18N
        jLabel238.setName("jLabel238"); // NOI18N

        jLoop.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jLoop.setText(resourceMap.getString("jLoop.text")); // NOI18N
        jLoop.setName("jLoop"); // NOI18N

        jLabel231.setText(resourceMap.getString("jLabel231.text")); // NOI18N
        jLabel231.setToolTipText(resourceMap.getString("jLabel231.toolTipText")); // NOI18N
        jLabel231.setName("jLabel231"); // NOI18N

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel226)
                    .addComponent(jLabel227)
                    .addComponent(jLabel230)
                    .addComponent(jLabel236)
                    .addComponent(jLabel237)
                    .addComponent(jLabel238)
                    .addComponent(jLabel231))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLoop)
                    .addComponent(jWeight, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSTMach, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTSMach, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .addComponent(jGamma, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel236)
                    .addComponent(jLabel237))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSTMach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel238))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel226)
                    .addComponent(jTSMach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel227)
                    .addComponent(jGamma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel230)
                    .addComponent(jTR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLoop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel231))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jFlightHeaderText.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jFlightHeaderText.border.title"))); // NOI18N
        jFlightHeaderText.setName("jFlightHeaderText"); // NOI18N

        jLabel228.setText(resourceMap.getString("jLabel228.text")); // NOI18N
        jLabel228.setToolTipText(resourceMap.getString("jLabel228.toolTipText")); // NOI18N
        jLabel228.setName("jLabel228"); // NOI18N

        jLabel229.setText(resourceMap.getString("jLabel229.text")); // NOI18N
        jLabel229.setToolTipText(resourceMap.getString("jLabel229.toolTipText")); // NOI18N
        jLabel229.setName("jLabel229"); // NOI18N

        jLabel239.setText(resourceMap.getString("jLabel239.text")); // NOI18N
        jLabel239.setToolTipText(resourceMap.getString("jLabel239.toolTipText")); // NOI18N
        jLabel239.setName("jLabel239"); // NOI18N

        jLabel240.setText(resourceMap.getString("jLabel240.text")); // NOI18N
        jLabel240.setToolTipText(resourceMap.getString("jLabel240.toolTipText")); // NOI18N
        jLabel240.setName("jLabel240"); // NOI18N

        jBlref.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jBlref.setText(resourceMap.getString("jBlref.text")); // NOI18N
        jBlref.setName("jBlref"); // NOI18N
        jBlref.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBlrefActionPerformed(evt);
            }
        });

        jSref.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jSref.setName("jSref"); // NOI18N

        jCbarr.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jCbarr.setName("jCbarr"); // NOI18N

        jRoughness.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Smooth", "Polished Metal", "Wood", "Sheet Metal", "Matte Paint", "Military Camoflauge, Standard", "Mliitary Camo, Spayed", "Dip-Galvanized Metal", "Cast Iron", " " }));
        jRoughness.setName("jRoughness"); // NOI18N

        javax.swing.GroupLayout jFlightHeaderTextLayout = new javax.swing.GroupLayout(jFlightHeaderText);
        jFlightHeaderText.setLayout(jFlightHeaderTextLayout);
        jFlightHeaderTextLayout.setHorizontalGroup(
            jFlightHeaderTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFlightHeaderTextLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFlightHeaderTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel229)
                    .addComponent(jLabel228)
                    .addComponent(jLabel240)
                    .addComponent(jLabel239))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jFlightHeaderTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jRoughness, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSref, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCbarr, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBlref, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jFlightHeaderTextLayout.setVerticalGroup(
            jFlightHeaderTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFlightHeaderTextLayout.createSequentialGroup()
                .addGroup(jFlightHeaderTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBlref, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel240))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jFlightHeaderTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSref, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel239))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jFlightHeaderTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel229)
                    .addComponent(jCbarr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jFlightHeaderTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel228)
                    .addComponent(jRoughness, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel55.setName("jPanel55"); // NOI18N

        jTitle.setFont(resourceMap.getFont("jTitle.font")); // NOI18N
        jTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTitle.setText(resourceMap.getString("jTitle.text")); // NOI18N
        jTitle.setName("jTitle"); // NOI18N

        javax.swing.GroupLayout jPanel55Layout = new javax.swing.GroupLayout(jPanel55);
        jPanel55.setLayout(jPanel55Layout);
        jPanel55Layout.setHorizontalGroup(
            jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel55Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel55Layout.setVerticalGroup(
            jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel55Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel55, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jFlightHeaderText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFlightHeaderText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jWeightActionPerformed

    private void jBlrefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBlrefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBlrefActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jBlref;
    private javax.swing.JTextField jCbarr;
    private javax.swing.JPanel jFlightHeaderText;
    private javax.swing.JTextField jGamma;
    private javax.swing.JLabel jLabel226;
    private javax.swing.JLabel jLabel227;
    private javax.swing.JLabel jLabel228;
    private javax.swing.JLabel jLabel229;
    private javax.swing.JLabel jLabel230;
    private javax.swing.JLabel jLabel231;
    private javax.swing.JLabel jLabel236;
    private javax.swing.JLabel jLabel237;
    private javax.swing.JLabel jLabel238;
    private javax.swing.JLabel jLabel239;
    private javax.swing.JLabel jLabel240;
    private javax.swing.JTextField jLoop;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel55;
    private static javax.swing.JComboBox jRoughness;
    private javax.swing.JTextField jSTMach;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jSref;
    private javax.swing.JTextField jTR;
    private javax.swing.JTextField jTSMach;
    private javax.swing.JTable jTable;
    private javax.swing.JLabel jTitle;
    private javax.swing.JTextField jWeight;
    // End of variables declaration//GEN-END:variables

    public static FlightConditionsView getInstance(){
        if(self == null)
        {
            self = new FlightConditionsView();
        }
        return self;
    }
}

