/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FlightConditionsView.java
 *
 * Created on Oct 14, 2009, 12:03:47 AM
 */

package FLTCON_Component;

import Abstracts.OAE_DataLink;
import Abstracts.OAE_LinkedTable;
import javax.swing.JComboBox;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author -B-
 */
public class FlightConditionsView extends javax.swing.JPanel
{
    String outputData;
    FlightConditionsController controller;
    
    /** Creates new form FlightConditionsView */
    public FlightConditionsView(FlightConditionsController controller) {
        initComponents();
        this.controller = controller;

        controller.createLink("BLREF",  jBlrefText,  double.class);
        controller.createLink("CBARR",  jCbarrText,  double.class);
        controller.createLink("GAMMA",  jGammaText,  double.class);
        controller.createLink(new OAE_LinkedTable(jTable1, 0, "AOA"));
        controller.createLink(new OAE_LinkedTable(jTable1, 1, "ALT"));
        controller.createLink(new OAE_LinkedTable(jTable1, 2, "MACH"));
        controller.createLink("SREF",   jSrefText,   double.class);
        controller.createLink("TR",     jTRText,     double.class);
        controller.createLink("TSMACH", jTSMachText, double.class);
        controller.createLink("WEIGHT", jWeightText, double.class);
        controller.createLink("LOOP",   jLoop,       double.class);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel13 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel17 = new javax.swing.JPanel();
        jWeightText = new javax.swing.JTextField();
        jSTMachText = new javax.swing.JTextField();
        jLabel226 = new javax.swing.JLabel();
        jTSMachText = new javax.swing.JTextField();
        jLabel227 = new javax.swing.JLabel();
        jGammaText = new javax.swing.JTextField();
        jLabel230 = new javax.swing.JLabel();
        jTRText = new javax.swing.JTextField();
        jLabel236 = new javax.swing.JLabel();
        jLabel237 = new javax.swing.JLabel();
        jLabel238 = new javax.swing.JLabel();
        jFlightHeaderText = new javax.swing.JPanel();
        jLabel228 = new javax.swing.JLabel();
        jLabel229 = new javax.swing.JLabel();
        jLabel239 = new javax.swing.JLabel();
        jLabel240 = new javax.swing.JLabel();
        jBlrefText = new javax.swing.JTextField();
        jSrefText = new javax.swing.JTextField();
        jCbarrText = new javax.swing.JTextField();
        jRoughness = new javax.swing.JComboBox();
        jLabel231 = new javax.swing.JLabel();
        jLoop = new javax.swing.JTextField();
        jPanel55 = new javax.swing.JPanel();
        jTitle = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(800, 600));

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(opendatcom.OpenDatcomController.class).getContext().getResourceMap(FlightConditionsView.class);
        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel13.border.title"))); // NOI18N
        jPanel13.setName("jPanel13"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "AOA", "Altitude", "Mach"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setName("jTable1"); // NOI18N
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel17.border.title"))); // NOI18N
        jPanel17.setName("jPanel17"); // NOI18N

        jWeightText.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jWeightText.setText(resourceMap.getString("jWeightText.text")); // NOI18N
        jWeightText.setName("jWeightText"); // NOI18N
        jWeightText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jWeightTextActionPerformed(evt);
            }
        });

        jSTMachText.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jSTMachText.setName("jSTMachText"); // NOI18N

        jLabel226.setText(resourceMap.getString("jLabel226.text")); // NOI18N
        jLabel226.setToolTipText(resourceMap.getString("jLabel226.toolTipText")); // NOI18N
        jLabel226.setName("jLabel226"); // NOI18N

        jTSMachText.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTSMachText.setName("jTSMachText"); // NOI18N

        jLabel227.setText(resourceMap.getString("jLabel227.text")); // NOI18N
        jLabel227.setToolTipText(resourceMap.getString("jLabel227.toolTipText")); // NOI18N
        jLabel227.setName("jLabel227"); // NOI18N

        jGammaText.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jGammaText.setName("jGammaText"); // NOI18N

        jLabel230.setText(resourceMap.getString("jLabel230.text")); // NOI18N
        jLabel230.setToolTipText(resourceMap.getString("jLabel230.toolTipText")); // NOI18N
        jLabel230.setName("jLabel230"); // NOI18N

        jTRText.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTRText.setName("jTRText"); // NOI18N

        jLabel236.setName("jLabel236"); // NOI18N

        jLabel237.setText(resourceMap.getString("jLabel237.text")); // NOI18N
        jLabel237.setToolTipText(resourceMap.getString("jLabel237.toolTipText")); // NOI18N
        jLabel237.setName("jLabel237"); // NOI18N

        jLabel238.setText(resourceMap.getString("jLabel238.text")); // NOI18N
        jLabel238.setToolTipText(resourceMap.getString("jLabel238.toolTipText")); // NOI18N
        jLabel238.setName("jLabel238"); // NOI18N

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel226)
                    .addComponent(jLabel227)
                    .addComponent(jLabel230)
                    .addComponent(jLabel236)
                    .addComponent(jLabel237)
                    .addComponent(jLabel238))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jWeightText)
                    .addComponent(jSTMachText)
                    .addComponent(jTSMachText)
                    .addComponent(jTRText, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .addComponent(jGammaText))
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jWeightText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel236)
                    .addComponent(jLabel237))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSTMachText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel238))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel226)
                    .addComponent(jTSMachText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel227)
                    .addComponent(jGammaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel230)
                    .addComponent(jTRText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jFlightHeaderText.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jFlightHeaderText.border.title"))); // NOI18N
        jFlightHeaderText.setName("jFlightHeaderText"); // NOI18N

        jLabel228.setText(resourceMap.getString("jLabel228.text")); // NOI18N
        jLabel228.setToolTipText(resourceMap.getString("jLabel228.toolTipText")); // NOI18N
        jLabel228.setName("jLabel228"); // NOI18N

        jLabel229.setText(resourceMap.getString("jLabel229.text")); // NOI18N
        jLabel229.setToolTipText(resourceMap.getString("jLabel229.toolTipText")); // NOI18N
        jLabel229.setName("jLabel229"); // NOI18N

        jLabel239.setText(resourceMap.getString("jLabel239.text")); // NOI18N
        jLabel239.setToolTipText(resourceMap.getString("jLabel239.toolTipText")); // NOI18N
        jLabel239.setName("jLabel239"); // NOI18N

        jLabel240.setText(resourceMap.getString("jLabel240.text")); // NOI18N
        jLabel240.setToolTipText(resourceMap.getString("jLabel240.toolTipText")); // NOI18N
        jLabel240.setName("jLabel240"); // NOI18N

        jBlrefText.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jBlrefText.setText(resourceMap.getString("jBlrefText.text")); // NOI18N
        jBlrefText.setName("jBlrefText"); // NOI18N
        jBlrefText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBlrefTextActionPerformed(evt);
            }
        });

        jSrefText.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jSrefText.setName("jSrefText"); // NOI18N

        jCbarrText.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jCbarrText.setName("jCbarrText"); // NOI18N

        jRoughness.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Smooth", "Polished Metal", "Wood", "Sheet Metal", "Matte Paint", "Military Camoflauge, Standard", "Mliitary Camo, Spayed", "Dip-Galvanized Metal", "Cast Iron", " " }));
        jRoughness.setName("jRoughness"); // NOI18N

        jLabel231.setText(resourceMap.getString("jLabel231.text")); // NOI18N
        jLabel231.setToolTipText(resourceMap.getString("jLabel231.toolTipText")); // NOI18N
        jLabel231.setName("jLabel231"); // NOI18N

        jLoop.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jLoop.setText(resourceMap.getString("jLoop.text")); // NOI18N
        jLoop.setName("jLoop"); // NOI18N

        javax.swing.GroupLayout jFlightHeaderTextLayout = new javax.swing.GroupLayout(jFlightHeaderText);
        jFlightHeaderText.setLayout(jFlightHeaderTextLayout);
        jFlightHeaderTextLayout.setHorizontalGroup(
            jFlightHeaderTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFlightHeaderTextLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFlightHeaderTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel229)
                    .addComponent(jLabel228)
                    .addComponent(jLabel240)
                    .addComponent(jLabel239)
                    .addComponent(jLabel231))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(jFlightHeaderTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLoop)
                    .addComponent(jRoughness, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSrefText, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCbarrText, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBlrefText, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE))
                .addContainerGap())
        );
        jFlightHeaderTextLayout.setVerticalGroup(
            jFlightHeaderTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFlightHeaderTextLayout.createSequentialGroup()
                .addGroup(jFlightHeaderTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBlrefText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel240))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jFlightHeaderTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSrefText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel239))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jFlightHeaderTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel229)
                    .addComponent(jCbarrText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jFlightHeaderTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel228)
                    .addComponent(jRoughness, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jFlightHeaderTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLoop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel231))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel55.setName("jPanel55"); // NOI18N

        jTitle.setFont(resourceMap.getFont("jTitle.font")); // NOI18N
        jTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTitle.setText(resourceMap.getString("jTitle.text")); // NOI18N
        jTitle.setName("jTitle"); // NOI18N

        javax.swing.GroupLayout jPanel55Layout = new javax.swing.GroupLayout(jPanel55);
        jPanel55.setLayout(jPanel55Layout);
        jPanel55Layout.setHorizontalGroup(
            jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel55Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel55Layout.setVerticalGroup(
            jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel55Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel55, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jFlightHeaderText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jFlightHeaderText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jWeightTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jWeightTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jWeightTextActionPerformed

    private void jBlrefTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBlrefTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBlrefTextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jBlrefText;
    private javax.swing.JTextField jCbarrText;
    private javax.swing.JPanel jFlightHeaderText;
    private javax.swing.JTextField jGammaText;
    private javax.swing.JLabel jLabel226;
    private javax.swing.JLabel jLabel227;
    private javax.swing.JLabel jLabel228;
    private javax.swing.JLabel jLabel229;
    private javax.swing.JLabel jLabel230;
    private javax.swing.JLabel jLabel231;
    private javax.swing.JLabel jLabel236;
    private javax.swing.JLabel jLabel237;
    private javax.swing.JLabel jLabel238;
    private javax.swing.JLabel jLabel239;
    private javax.swing.JLabel jLabel240;
    private javax.swing.JTextField jLoop;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel55;
    private static javax.swing.JComboBox jRoughness;
    private javax.swing.JTextField jSTMachText;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jSrefText;
    private javax.swing.JTextField jTRText;
    private javax.swing.JTextField jTSMachText;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jTitle;
    private javax.swing.JTextField jWeightText;
    // End of variables declaration//GEN-END:variables

    public JTextArea getjAOAText() {
        return null;
    }

    public JTextArea getjAltText() {
        return null;
    }

    public JTextField getjGammaText() {
        return jGammaText;
    }

    public JTextField getjWeightText() {
        return jWeightText;
    }

    public JTextArea getjMachText() {
        return null;
    }

    public JTextField getjSTMachText() {
        return jSTMachText;
    }

    public JTextField getjTRText() {
        return jTRText;
    }

    public JTextField getjTSMachText() {
        return jTSMachText;
    }

    public String getOutputData() {
        return outputData;
    }

    public void setOutputData(String outputData) {
        this.outputData = outputData;
    }

    public JTextField getjBlrefText() {
        return jBlrefText;
    }

    public JTextField getjCbarrText() {
        return jCbarrText;
    }

    public JTextField getjSrefText() {
        return jSrefText;
    }

    public JComboBox getjRoughness() {
        return jRoughness;
    }

    public JTextField getjLoop() {
        return jLoop;
    }
    
}

